# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7506669c285548bda8ed855ca3f5b971fcb9297c4592bee879a31a138eb653ead5432b82721b65cf89046638a824f6d65a063746a9aef7954f5cf0b67953aa90

test:
  secret_key_base: 61f76e5933dcbb3eba7ace1bade307b03b8d90cdd3b39310b92581ec6ca0bb20348a404441dfa2968a72cd549372aaffe167683acc0ded852d3173cab63c45bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
